version: '2'
services:
    jasper_microservice-app:
        image: jasper_microservice
        external_links:
            - jasper_microservice-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jasper_microservice
    jasper_microservice-postgresql:
        extends:
            file: postgresql.yml
            service: jasper_microservice-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
